package io.ryanjames.oak.audio;

import io.ryanjames.oak.VideoConfig;
import io.ryanjames.oak.config.GlobalConfig;
import io.ryanjames.oak.midi.MidiFile;
import org.junit.jupiter.api.Test;

import javax.sound.midi.Sequence;
import java.io.File;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class AudioPipelineTest {

    @Test
    void run_usesConfiguredAudioFilePathWhenPresent() {
        VideoConfig videoConfig = new VideoConfig();
        videoConfig.setAudioFilePath("custom/path.wav");
        GlobalConfig globalConfig = new GlobalConfig("out", videoConfig, null);

        File expected = new File("custom/path.wav");
        AudioPipeline pipeline = new AudioPipeline(globalConfig);

        File result = pipeline.run(null);

        assertEquals(expected.getPath(), result.getPath());
    }

    @Test
    void run_createsWavWhenAudioFilePathMissing() throws Exception {
        VideoConfig videoConfig = new VideoConfig();
        videoConfig.setAudioFilePath(null);
        GlobalConfig globalConfig = new GlobalConfig("out", videoConfig, null);

        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        MidiFile midiFile = buildMidiFile(sequence);
        File expected = new File("temp.wav");

        AtomicReference<Sequence> capturedSequence = new AtomicReference<>();
        AudioPipeline pipeline = new AudioPipeline(globalConfig) {
            @Override
            protected File createWav(Sequence seq) {
                capturedSequence.set(seq);
                return expected;
            }
        };

        File result = pipeline.run(midiFile);

        assertSame(expected, result);
        assertSame(sequence, capturedSequence.get());
    }

    @Test
    void run_propagatesAudioRenderingExceptionFromCreateWav() throws Exception {
        VideoConfig videoConfig = new VideoConfig();
        videoConfig.setAudioFilePath("");
        GlobalConfig globalConfig = new GlobalConfig("out", videoConfig, null);

        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        MidiFile midiFile = buildMidiFile(sequence);

        AudioRenderingException expected = new AudioRenderingException("boom");
        AudioPipeline pipeline = new AudioPipeline(globalConfig) {
            @Override
            protected File createWav(Sequence seq) {
                throw expected;
            }
        };

        AudioRenderingException thrown = org.junit.jupiter.api.Assertions.assertThrows(
                AudioRenderingException.class,
                () -> pipeline.run(midiFile)
        );

        assertSame(expected, thrown);
    }

    private static MidiFile buildMidiFile(Sequence sequence) throws Exception {
        var constructor = MidiFile.class.getDeclaredConstructor(
                File.class,
                Sequence.class,
                int.class,
                double.class,
                double.class
        );
        constructor.setAccessible(true);
        return constructor.newInstance(new File("test.mid"), sequence, 480, 120.0, 1.0);
    }
}
