package io.ryanjames.oak.color;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class ColorRangeTest {

    @Test
    void constructor_confinesBoundsAndKeepsOrder() {
        ColorRange range = new ColorRange(-5, ColorRange.getMaxValue() + 10);

        assertEquals(ColorRange.getMinValue(), range.getLowerBound());
        assertEquals(ColorRange.getMaxValue(), range.getUpperBound());
    }

    @Test
    void constructor_swapsBoundsWhenOutOfOrder() {
        ColorRange range = new ColorRange(100, 10);

        assertEquals(10, range.getLowerBound());
        assertEquals(100, range.getUpperBound());
    }

    @Test
    void isWithinBounds_acceptsInclusiveEdgesAndNormalizesUnsignedColor() {
        ColorRange range = new ColorRange(0x000000, 0x0000FF);

        assertTrue(range.isWithinBounds(0));
        assertTrue(range.isWithinBounds(0x0000FF));
        assertFalse(range.isWithinBounds(0x000100));
        assertTrue(range.isWithinBounds(0xFF0000FF));
    }

    @Test
    void getFullRange_coversAllRgbValues() {
        ColorRange range = ColorRange.getFullRange();

        assertTrue(range.isWithinBounds(ColorRange.getMinValue()));
        assertTrue(range.isWithinBounds(ColorRange.getMaxValue()));
        assertTrue(range.isWithinBounds(-1));
    }
}
