package io.ryanjames.oak.image;

import org.junit.jupiter.api.Test;

import java.awt.Color;
import java.awt.image.BufferedImage;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotSame;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class ImageCopierTest {

    @Test
    void copyImage_clonesPixelsAndDimensions() {
        BufferedImage original = new BufferedImage(2, 2, BufferedImage.TYPE_INT_ARGB);
        original.setRGB(0, 0, new Color(255, 0, 0, 255).getRGB());
        original.setRGB(1, 0, new Color(0, 255, 0, 255).getRGB());
        original.setRGB(0, 1, new Color(0, 0, 255, 255).getRGB());
        original.setRGB(1, 1, new Color(255, 255, 0, 128).getRGB());

        BufferedImage copy = ImageCopier.copyImage(original);

        assertNotSame(original, copy);
        assertEquals(original.getWidth(), copy.getWidth());
        assertEquals(original.getHeight(), copy.getHeight());
        assertEquals(original.getRGB(0, 0), copy.getRGB(0, 0));
        assertEquals(original.getRGB(1, 0), copy.getRGB(1, 0));
        assertEquals(original.getRGB(0, 1), copy.getRGB(0, 1));
        assertEquals(original.getRGB(1, 1), copy.getRGB(1, 1));
    }
}

