package io.ryanjames.oak.image;

import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.file.Files;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class ImageLayeringTest {

    @Test
    void addBackground_returnsCompositeWithForegroundOnTop() throws Exception {
        BufferedImage foreground = new BufferedImage(2, 2, BufferedImage.TYPE_INT_ARGB);
        foreground.setRGB(0, 0, new Color(255, 0, 0, 255).getRGB());
        foreground.setRGB(1, 0, new Color(0, 0, 0, 0).getRGB());

        BufferedImage background = new BufferedImage(2, 2, BufferedImage.TYPE_INT_ARGB);
        background.setRGB(0, 0, new Color(0, 255, 0, 255).getRGB());
        background.setRGB(1, 0, new Color(0, 0, 255, 255).getRGB());

        File tempFile = Files.createTempFile("oak-bg", ".png").toFile();
        ImageIO.write(background, "png", tempFile);

        BufferedImage composite = ImageLayering.addBackground(foreground, tempFile);

        assertEquals(foreground.getRGB(0, 0), composite.getRGB(0, 0));
        assertEquals(background.getRGB(1, 0), composite.getRGB(1, 0));
    }

    @Test
    void addBackground_scalesBackgroundToForegroundSize() throws Exception {
        BufferedImage foreground = new BufferedImage(2, 2, BufferedImage.TYPE_INT_ARGB);
        foreground.setRGB(0, 0, new Color(255, 0, 0, 255).getRGB());

        BufferedImage background = new BufferedImage(4, 4, BufferedImage.TYPE_INT_ARGB);
        background.setRGB(0, 0, new Color(0, 255, 0, 255).getRGB());

        File tempFile = Files.createTempFile("oak-bg", ".png").toFile();
        ImageIO.write(background, "png", tempFile);

        BufferedImage composite = ImageLayering.addBackground(foreground, tempFile);

        assertEquals(2, composite.getWidth());
        assertEquals(2, composite.getHeight());
        assertEquals(foreground.getRGB(0, 0), composite.getRGB(0, 0));
    }

    @Test
    void addBackground_throwsOnMissingFile() {
        File missing = new File("missing-background-file.png");

        assertThrows(ImageProcessingException.class, () ->
                ImageLayering.addBackground(new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB), missing)
        );
    }
}

