package io.ryanjames.oak.image;

import org.junit.jupiter.api.Test;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class ImagePadderTest {

    @Test
    void padImages_addsBlankImagesToReachGridSize() throws Exception {
        BufferedImage base = new BufferedImage(2, 3, BufferedImage.TYPE_INT_ARGB);
        base.setRGB(0, 0, new Color(10, 20, 30, 40).getRGB());

        List<BufferedImage> images = new ArrayList<>(List.of(base));

        List<BufferedImage> result = ImagePadder.padImages(images, 2, 2);

        assertSame(images, result);
        assertEquals(4, result.size());
        assertEquals(2, result.get(1).getWidth());
        assertEquals(3, result.get(1).getHeight());
    }

    @Test
    void padImages_noPaddingWhenAtCapacity() throws Exception {
        BufferedImage base = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        List<BufferedImage> images = new ArrayList<>(List.of(base, base, base, base));

        List<BufferedImage> result = ImagePadder.padImages(images, 2, 2);

        assertSame(images, result);
        assertEquals(4, result.size());
    }

    @Test
    void padImageTop_increasesHeightAndPlacesOriginalBelowPadding() {
        BufferedImage image = new BufferedImage(2, 2, BufferedImage.TYPE_INT_ARGB);
        image.setRGB(0, 0, new Color(255, 0, 0, 255).getRGB());

        BufferedImage padded = ImagePadder.padImageTop(image, 1);

        assertEquals(2, padded.getWidth());
        assertEquals(3, padded.getHeight());
        assertEquals(image.getRGB(0, 0), padded.getRGB(0, 1));
    }

    @Test
    void padImageBottom_increasesHeightAndKeepsOriginalAtTop() {
        BufferedImage image = new BufferedImage(2, 2, BufferedImage.TYPE_INT_ARGB);
        image.setRGB(1, 1, new Color(0, 255, 0, 255).getRGB());

        BufferedImage padded = ImagePadder.padImageBottom(image, 1);

        assertEquals(2, padded.getWidth());
        assertEquals(3, padded.getHeight());
        assertEquals(image.getRGB(1, 1), padded.getRGB(1, 1));
    }
}
