package io.ryanjames.oak.image;

import org.junit.jupiter.api.Test;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class ImageScalerTest {

    @Test
    void scale_returnsNullWhenImageIsNull() {
        assertNull(ImageScaler.scale(null, 10, 10));
    }

    @Test
    void scale_resizesAndPreservesTopLeftPixel() {
        BufferedImage original = new BufferedImage(2, 2, BufferedImage.TYPE_INT_ARGB);
        original.setRGB(0, 0, new Color(10, 20, 30, 255).getRGB());

        BufferedImage scaled = ImageScaler.scale(original, 4, 3);

        assertEquals(4, scaled.getWidth());
        assertEquals(3, scaled.getHeight());
        assertEquals(original.getRGB(0, 0), scaled.getRGB(0, 0));
    }

    @Test
    void scaleAll_scalesEachImageAndKeepsCount() {
        BufferedImage img1 = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        BufferedImage img2 = new BufferedImage(2, 2, BufferedImage.TYPE_INT_ARGB);
        List<BufferedImage> images = new ArrayList<>(List.of(img1, img2));

        List<BufferedImage> scaled = ImageScaler.scaleAll(images, 5, 6);

        assertEquals(2, scaled.size());
        assertEquals(5, scaled.get(0).getWidth());
        assertEquals(6, scaled.get(0).getHeight());
        assertEquals(5, scaled.get(1).getWidth());
        assertEquals(6, scaled.get(1).getHeight());
    }
}
