package io.ryanjames.oak.image;

import io.ryanjames.oak.CustomText;
import io.ryanjames.oak.VideoConfig;
import io.ryanjames.oak.config.GlobalConfig;
import io.ryanjames.oak.midi.MidiFile;
import io.ryanjames.oak.midi.MidiNote;
import io.ryanjames.oak.midi.MidiNoteExtractor;
import io.ryanjames.oak.video.VideoFramePipeline;
import org.junit.jupiter.api.Test;

import javax.sound.midi.Sequence;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class VideoFramePipelineTest {

    @Test
    void run_prependsInitialDurationAndAddsFinalDurationWhenMissing() throws Exception {
        ArrayList<BufferedImage> frames = new ArrayList<>(List.of(
                new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB),
                new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB),
                new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB)
        ));

        ArrayList<Double> durations = new ArrayList<>();
        durations.add(500.0);

        MidiNoteExtractor.Result noteInfo = new MidiNoteExtractor.Result(0, 0, 0, 0, List.of(), List.of());
        MidiFile midiFile = buildMidiFile(new Sequence(Sequence.PPQ, 480));

        VideoFramePipeline pipeline = new VideoFramePipeline(buildGlobalConfig()) {
            @Override
            public List<BufferedImage> createImageFrames(MidiNoteExtractor.Result info, File background) {
                return frames;
            }

            @Override
            protected List<Double> getFrameDurations(MidiFile midi, List<MidiNote> on, List<MidiNote> off) {
                return durations;
            }

            @Override
            protected List<BufferedImage> createVideoFrames(
                    List<BufferedImage> imageFrames, List<Double> frameDurations) {
                return imageFrames;
            }
        };

        VideoFramePipeline.Result result = pipeline.run(midiFile, noteInfo, new File("bg.png"));

        assertEquals(3, result.frameDurationsMs().size());
        assertEquals(2000.0, result.frameDurationsMs().get(0));
        assertEquals(500.0, result.frameDurationsMs().get(1));
        assertEquals(2000.0, result.frameDurationsMs().get(2));
        assertSame(frames, result.videoFrames());
    }

    @Test
    void run_doesNotAppendDurationWhenCountsMatch() throws Exception {
        ArrayList<BufferedImage> frames = new ArrayList<>(List.of(
                new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB),
                new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB)
        ));

        ArrayList<Double> durations = new ArrayList<>();
        durations.add(500.0);

        MidiNoteExtractor.Result noteInfo = new MidiNoteExtractor.Result(0, 0, 0, 0, List.of(), List.of());
        MidiFile midiFile = buildMidiFile(new Sequence(Sequence.PPQ, 480));

        VideoFramePipeline pipeline = new VideoFramePipeline(buildGlobalConfig()) {
            @Override
            public List<BufferedImage> createImageFrames(MidiNoteExtractor.Result info, File background) {
                return frames;
            }

            @Override
            protected List<Double> getFrameDurations(MidiFile midi, List<MidiNote> on, List<MidiNote> off) {
                return durations;
            }

            @Override
            protected List<BufferedImage> createVideoFrames(
                    List<BufferedImage> imageFrames, List<Double> frameDurations) {
                return imageFrames;
            }
        };

        VideoFramePipeline.Result result = pipeline.run(midiFile, noteInfo, new File("bg.png"));

        assertEquals(2, result.frameDurationsMs().size());
        assertEquals(2000.0, result.frameDurationsMs().get(0));
        assertEquals(500.0, result.frameDurationsMs().get(1));
        assertSame(frames, result.videoFrames());
    }

    @Test
    void getFrameDurations_includesIntroAndOutroCounts() throws Exception {
        ArrayList<String> originalIntro = new ArrayList<>(CustomText.getIntroText());
        ArrayList<String> originalOutro = new ArrayList<>(CustomText.getOutroText());
        CustomText.setIntroText(new ArrayList<>(List.of("one", "two")));
        CustomText.setOutroText(new ArrayList<>(List.of("out")));

        try {
            ArrayList<MidiNote> onNotes = new ArrayList<>();
            ArrayList<MidiNote> offNotes = new ArrayList<>();

            MidiFile midiFile = buildMidiFile(new Sequence(Sequence.PPQ, 480));

            class TestPipeline extends VideoFramePipeline {
                TestPipeline(GlobalConfig config) {
                    super(config);
                }

                List<Double> exposeDurations(MidiFile midi, List<MidiNote> on, List<MidiNote> off) {
                    return getFrameDurations(midi, on, off);
                }
            }

            TestPipeline pipeline = new TestPipeline(buildGlobalConfig());
            List<Double> durations = pipeline.exposeDurations(midiFile, onNotes, offNotes);

            assertEquals(3, durations.size());
            assertEquals(1000.0, durations.get(0));
            assertEquals(1000.0, durations.get(1));
            assertEquals(1000.0, durations.get(2));
        } finally {
            CustomText.setIntroText(originalIntro);
            CustomText.setOutroText(originalOutro);
        }
    }

    private static GlobalConfig buildGlobalConfig() {
        VideoConfig videoConfig = new VideoConfig();
        return new GlobalConfig("out", videoConfig, null);
    }

    private static MidiFile buildMidiFile(Sequence sequence) throws Exception {
        var constructor = MidiFile.class.getDeclaredConstructor(
                File.class,
                Sequence.class,
                int.class,
                double.class,
                double.class
        );
        constructor.setAccessible(true);
        return constructor.newInstance(new File("test.mid"), sequence, 480, 120.0, 1.0);
    }
}
