package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.MetaMessage;
import javax.sound.midi.MidiEvent;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class EndSilenceTrimmerTest {

    @Test
    void transform_trimsEventsAfterAllowedSilence() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        addNoteOn(track, 0, 60, 64, 0);
        addNoteOff(track, 0, 60, 64, 480);
        track.add(new MidiEvent(endOfTrack(), 2000));

        EndSilenceTrimmer trimmer = new EndSilenceTrimmer(0.0);
        Sequence output = trimmer.transform(sequence);

        Track outTrack = output.getTracks()[0];
        assertTrue(hasEotAt(outTrack, 480));
        assertEquals(3, outTrack.size());
    }

    @Test
    void transform_keepsAllowedTrailingSilence() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        addNoteOn(track, 0, 60, 64, 0);
        addNoteOff(track, 0, 60, 64, 480);
        track.add(new MidiEvent(endOfTrack(), 2000));

        EndSilenceTrimmer trimmer = new EndSilenceTrimmer(500.0);
        Sequence output = trimmer.transform(sequence);

        Track outTrack = output.getTracks()[0];
        assertTrue(hasEotAt(outTrack, 960));
    }

    private static boolean hasEotAt(Track track, long tick) {
        for (int i = 0; i < track.size(); i++) {
            MidiEvent ev = track.get(i);
            if (ev.getMessage() instanceof MetaMessage meta && meta.getType() == 0x2F) {
                return ev.getTick() == tick;
            }
        }
        return false;
    }

    private static void addNoteOn(Track track, int channel, int note, int velocity, long tick) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_ON, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }

    private static void addNoteOff(Track track, int channel, int note, int velocity, long tick) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_OFF, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }

    private static MetaMessage endOfTrack() throws Exception {
        MetaMessage eot = new MetaMessage();
        eot.setMessage(0x2F, new byte[0], 0);
        return eot;
    }
}

