package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MetaMessage;
import javax.sound.midi.MidiEvent;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class FirstChannelTakerTransformerTest {

    @Test
    void transform_keepsOnlyFirstNoteOnChannelShortMessagesAndMeta() throws Exception {
        Sequence input = new Sequence(Sequence.PPQ, 480);
        Track track = input.createTrack();

        MetaMessage meta = new MetaMessage();
        meta.setMessage(0x03, "name".getBytes(), "name".length());
        track.add(new MidiEvent(meta, 0));

        // First channel message is not NOTE_ON; channel 1 should still be chosen
        // because the first NOTE_ON uses channel 1.
        track.add(new MidiEvent(shortMessage(ShortMessage.PROGRAM_CHANGE, 2, 5, 0), 0));
        track.add(new MidiEvent(shortMessage(ShortMessage.NOTE_ON, 1, 60, 64), 5));
        track.add(new MidiEvent(shortMessage(ShortMessage.NOTE_ON, 0, 61, 64), 10));
        track.add(new MidiEvent(shortMessage(ShortMessage.NOTE_OFF, 1, 60, 0), 15));

        FirstChannelTakerTransformer transformer = new FirstChannelTakerTransformer();
        Sequence output = transformer.transform(input);

        Track outTrack = output.getTracks()[0];
        assertEquals(input.getTracks().length, output.getTracks().length);
        assertEquals(input.getDivisionType(), output.getDivisionType());
        assertEquals(input.getResolution(), output.getResolution());

        List<ShortMessage> shortMessages = new ArrayList<>();
        boolean hasMetaName = false;
        boolean hasEot = false;

        for (int i = 0; i < outTrack.size(); i++) {
            if (outTrack.get(i).getMessage() instanceof ShortMessage sm) {
                shortMessages.add(sm);
            }
            if (outTrack.get(i).getMessage() instanceof MetaMessage mm) {
                if (mm.getType() == 0x03) {
                    hasMetaName = true;
                }
                if (mm.getType() == 0x2F) {
                    hasEot = true;
                }
            }
        }

        assertTrue(hasMetaName);
        assertTrue(hasEot);
        assertEquals(2, shortMessages.size());
        assertEquals(1, shortMessages.get(0).getChannel());
        assertEquals(1, shortMessages.get(1).getChannel());
    }

    @Test
    void transform_keepsOnlyMetaWhenNoNoteOnExists() throws Exception {
        Sequence input = new Sequence(Sequence.PPQ, 480);
        Track track = input.createTrack();

        MetaMessage meta = new MetaMessage();
        meta.setMessage(0x03, "title".getBytes(), "title".length());
        track.add(new MidiEvent(meta, 0));

        track.add(new MidiEvent(shortMessage(ShortMessage.CONTROL_CHANGE, 7, 7, 100), 0));
        track.add(new MidiEvent(shortMessage(ShortMessage.PROGRAM_CHANGE, 7, 9, 0), 5));

        FirstChannelTakerTransformer transformer = new FirstChannelTakerTransformer();
        Sequence output = transformer.transform(input);

        Track outTrack = output.getTracks()[0];
        int shortCount = 0;
        boolean hasMetaName = false;
        boolean hasEot = false;

        for (int i = 0; i < outTrack.size(); i++) {
            if (outTrack.get(i).getMessage() instanceof ShortMessage) {
                shortCount++;
            }
            if (outTrack.get(i).getMessage() instanceof MetaMessage mm) {
                if (mm.getType() == 0x03) {
                    hasMetaName = true;
                }
                if (mm.getType() == 0x2F) {
                    hasEot = true;
                }
            }
        }

        assertEquals(0, shortCount);
        assertTrue(hasMetaName);
        assertTrue(hasEot);
    }

    private static ShortMessage shortMessage(int command, int channel, int data1, int data2)
            throws InvalidMidiDataException {
        ShortMessage message = new ShortMessage();
        message.setMessage(command, channel, data1, data2);
        return message;
    }
}

