package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MetaMessage;
import javax.sound.midi.MidiEvent;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class FirstTrackOnlyTransformerTest {

    @Test
    void transform_keepsOnlyFirstTrackEventsAndAddsEot() throws Exception {
        Sequence input = new Sequence(Sequence.PPQ, 480, 2);
        Track first = input.getTracks()[0];
        Track second = input.getTracks()[1];

        MetaMessage name = new MetaMessage();
        name.setMessage(0x03, "first".getBytes(), "first".length());
        first.add(new MidiEvent(name, 0));
        first.add(new MidiEvent(shortMessage(ShortMessage.NOTE_ON, 0, 60, 64), 10));

        second.add(new MidiEvent(shortMessage(ShortMessage.NOTE_ON, 1, 62, 64), 5));

        FirstTrackOnlyTransformer transformer = new FirstTrackOnlyTransformer();
        Sequence output = transformer.transform(input);

        assertEquals(1, output.getTracks().length);
        assertEquals(input.getDivisionType(), output.getDivisionType());
        assertEquals(input.getResolution(), output.getResolution());

        Track outTrack = output.getTracks()[0];
        List<ShortMessage> shortMessages = new ArrayList<>();
        boolean hasName = false;
        boolean hasEot = false;

        for (int i = 0; i < outTrack.size(); i++) {
            if (outTrack.get(i).getMessage() instanceof ShortMessage sm) {
                shortMessages.add(sm);
            }
            if (outTrack.get(i).getMessage() instanceof MetaMessage mm) {
                if (mm.getType() == 0x03) {
                    hasName = true;
                }
                if (mm.getType() == 0x2F) {
                    hasEot = true;
                }
            }
        }

        assertTrue(hasName);
        assertTrue(hasEot);
        assertEquals(1, shortMessages.size());
        assertEquals(0, shortMessages.get(0).getChannel());
        assertEquals(60, shortMessages.get(0).getData1());
    }

    @Test
    void transform_emptyInputCreatesSingleEmptyTrackWithEot() throws Exception {
        Sequence input = new Sequence(Sequence.PPQ, 480, 0);

        FirstTrackOnlyTransformer transformer = new FirstTrackOnlyTransformer();
        Sequence output = transformer.transform(input);

        assertEquals(1, output.getTracks().length);
        Track outTrack = output.getTracks()[0];
        boolean hasEot = false;

        for (int i = 0; i < outTrack.size(); i++) {
            if (outTrack.get(i).getMessage() instanceof MetaMessage mm && mm.getType() == 0x2F) {
                hasEot = true;
            }
        }

        assertTrue(hasEot);
    }

    private static ShortMessage shortMessage(int command, int channel, int data1, int data2)
            throws InvalidMidiDataException {
        ShortMessage message = new ShortMessage();
        message.setMessage(command, channel, data1, data2);
        return message;
    }
}

