package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import java.io.File;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class MapImageTest {

    @Test
    void altoCTwelve_mapsSharpsAndFlatsToSameSprite() {
        File sharp = MapImage.altoCTwelve("A#5");
        File flat = MapImage.altoCTwelve("Bb5");

        assertEquals(sharp.getPath(), flat.getPath());
    }

    @Test
    void altoCTwelve_mapsValidNotesToExpectedFiles() {
        assertEquals(new File("src/main/resources/Alto C Twelve/ocarina_sprite - A5.png").getPath(),
                MapImage.altoCTwelve("A5").getPath());
        assertEquals(new File("src/main/resources/Alto C Twelve/ocarina_sprite - C6.png").getPath(),
                MapImage.altoCTwelve("C6").getPath());
        assertEquals(new File("src/main/resources/Alto C Twelve/ocarina_sprite - F7.png").getPath(),
                MapImage.altoCTwelve("F7").getPath());
    }

    @Test
    void altoCTwelve_throwsForOutOfRangeNote() {
        assertThrows(OutOfRangeException.class, () -> MapImage.altoCTwelve("G7"));
    }
}
