package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MetaMessage;
import javax.sound.midi.MidiEvent;
import javax.sound.midi.MidiMessage;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.SysexMessage;
import javax.sound.midi.Track;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class MidiCopyUtilsTest {

    @Test
    void deepCopyMessage_copiesShortMessageFields() throws Exception {
        ShortMessage original = new ShortMessage();
        original.setMessage(ShortMessage.NOTE_ON, 2, 64, 100);

        MidiMessage copy = MidiCopyUtils.deepCopyMessage(original);

        assertTrue(copy instanceof ShortMessage);
        ShortMessage sm = (ShortMessage) copy;
        assertEquals(original.getCommand(), sm.getCommand());
        assertEquals(original.getChannel(), sm.getChannel());
        assertEquals(original.getData1(), sm.getData1());
        assertEquals(original.getData2(), sm.getData2());
        assertNotSame(original, sm);
    }

    @Test
    void deepCopyMessage_copiesMetaMessageTypeAndData() throws Exception {
        MetaMessage original = new MetaMessage();
        byte[] data = new byte[] {1, 2, 3};
        original.setMessage(0x03, data, data.length);

        MidiMessage copy = MidiCopyUtils.deepCopyMessage(original);

        assertTrue(copy instanceof MetaMessage);
        MetaMessage mm = (MetaMessage) copy;
        assertEquals(original.getType(), mm.getType());
        assertArrayEquals(original.getData(), mm.getData());
        assertNotSame(original, mm);
    }

    @Test
    void deepCopyMessage_copiesSysexMessageBytes() throws Exception {
        SysexMessage original = new SysexMessage();
        byte[] full = new byte[] {(byte) 0xF0, 0x01, 0x02, (byte) 0xF7};
        original.setMessage(full, full.length);

        MidiMessage copy = MidiCopyUtils.deepCopyMessage(original);

        assertTrue(copy instanceof SysexMessage);
        SysexMessage sx = (SysexMessage) copy;
        assertArrayEquals(original.getMessage(), sx.getMessage());
        assertNotSame(original, sx);
    }

    @Test
    void ensureEndOfTrack_addsEotWhenMissing() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();
        track.add(new MidiEvent(shortMessage(ShortMessage.NOTE_ON, 0, 60, 64), 10));

        MidiCopyUtils.ensureEndOfTrack(track);

        assertTrue(hasEot(track));
        assertEquals(2, track.size());
    }

    @Test
    void ensureEndOfTrack_doesNotDuplicateWhenPresent() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();
        track.add(new MidiEvent(shortMessage(ShortMessage.NOTE_ON, 0, 60, 64), 10));
        track.add(new MidiEvent(endOfTrackMessage(), 10));

        MidiCopyUtils.ensureEndOfTrack(track);

        assertTrue(hasEot(track));
        assertEquals(2, track.size());
    }

    @Test
    void singleTrackCopy_copiesEventsAndEnsuresEot() throws Exception {
        Sequence input = new Sequence(Sequence.PPQ, 480, 2);
        Track first = input.getTracks()[0];
        Track second = input.getTracks()[1];

        first.add(new MidiEvent(shortMessage(ShortMessage.NOTE_ON, 0, 60, 64), 5));
        second.add(new MidiEvent(shortMessage(ShortMessage.NOTE_ON, 1, 62, 64), 5));

        Sequence output = MidiCopyUtils.singleTrackCopy(input, first);

        assertEquals(1, output.getTracks().length);
        Track outTrack = output.getTracks()[0];
        assertTrue(hasEot(outTrack));
        assertEquals(2, outTrack.size());
    }

    private static boolean hasEot(Track track) {
        for (int i = 0; i < track.size(); i++) {
            MidiMessage msg = track.get(i).getMessage();
            if (msg instanceof MetaMessage meta && meta.getType() == 0x2F) {
                return true;
            }
        }
        return false;
    }

    private static ShortMessage shortMessage(int command, int channel, int data1, int data2)
            throws InvalidMidiDataException {
        ShortMessage message = new ShortMessage();
        message.setMessage(command, channel, data1, data2);
        return message;
    }

    private static MetaMessage endOfTrackMessage() throws InvalidMidiDataException {
        MetaMessage eot = new MetaMessage();
        eot.setMessage(0x2F, new byte[0], 0);
        return eot;
    }
}

