package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class MidiCommonTest {

    @Test
    void tuningFromPeaks_buildsExpectedCentValues() {
        double[] peaks = new double[] {0.0, 100.0, 200.0};

        double[] tuning = MidiCommon.tuningFromPeaks(peaks);

        assertEquals(128, tuning.length);
        assertEquals(4800.0, tuning[60]);
        assertEquals(4900.0, tuning[61]);
        assertEquals(3800.0, tuning[59]);
    }

    @Test
    void tuningFromPeaks_rejectsUnsortedPeaks() {
        double[] peaks = new double[] {0.0, 200.0, 100.0};

        assertThrows(IllegalArgumentException.class, () -> MidiCommon.tuningFromPeaks(peaks));
    }
}

