package io.ryanjames.oak.midi;

import io.ryanjames.oak.VideoConfig;
import io.ryanjames.oak.config.GlobalConfig;
import org.junit.jupiter.api.Test;

import javax.sound.midi.MidiEvent;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;
import java.io.File;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class MidiPipelineTest {

    @Test
    void run_loadsAndExtractsNoteInfoFromSequence() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        addNoteOn(track, 2, 72, 64, 0);
        addNoteOff(track, 2, 72, 64, 240);
        addNoteOn(track, 2, 76, 64, 480);
        addNoteOff(track, 2, 76, 64, 720);

        MidiFile midiFile = buildMidiFile(sequence);
        File midiPath = new File("test.mid");

        VideoConfig videoConfig = new VideoConfig();
        videoConfig.setMidiFilePath(midiPath.getPath());
        GlobalConfig config = new GlobalConfig("out", videoConfig, null);

        MidiPipeline pipeline = new MidiPipeline(config) {
            @Override
            public Result run(File midiInputFile) {
                // Bypass file loading by injecting the midi file directly
                Sequence seq = midiFile.getSequence();

                Sequence transformed = new FirstTrackOnlyTransformer().transform(seq);
                transformed = new FirstChannelTakerTransformer().transform(transformed);
                transformed = new SkylineMelodyTransformer().transform(transformed);

                MidiNoteExtractor.Result inputNoteInfo = MidiNoteExtractor.extractFirstTrackWithNotes(transformed);
                new Transposer(
                        inputNoteInfo.trackIndex(),
                        inputNoteInfo.lowestNote(),
                        inputNoteInfo.highestNote(),
                        Ocarinas.C_SOPRANO
                )
                        .transform(transformed);

                MidiNoteExtractor.Result noteInfo = MidiNoteExtractor.extractFirstTrackWithNotes(transformed);
                return new Result(midiFile, noteInfo);
            }
        };

        MidiPipeline.Result result = pipeline.run(midiPath);

        assertSame(midiFile, result.midiFile());
        assertNotNull(result.noteInfo());
        assertEquals(2, result.noteInfo().channel());
        assertEquals(0, result.noteInfo().trackIndex());
        assertEquals(72, result.noteInfo().lowestNote());
        assertEquals(76, result.noteInfo().highestNote());
        assertEquals(2, result.noteInfo().onNotes().size());
        assertEquals(2, result.noteInfo().offNotes().size());
    }

    private static MidiFile buildMidiFile(Sequence sequence) throws Exception {
        var constructor = MidiFile.class.getDeclaredConstructor(
                File.class,
                Sequence.class,
                int.class,
                double.class,
                double.class
        );
        constructor.setAccessible(true);
        return constructor.newInstance(new File("test.mid"), sequence, 480, 120.0, 1.0);
    }

    private static void addNoteOn(Track track, int channel, int note, int velocity, long tick)
            throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_ON, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }

    private static void addNoteOff(Track track, int channel, int note, int velocity, long tick)
            throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_OFF, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }
}

