package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.MetaMessage;
import javax.sound.midi.MidiEvent;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class MidiKeyGuesserTest {

    @Test
    void detectKey_prefersKeySignatureWhenPresent() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        track.add(new MidiEvent(keySignatureEvent(0, 0), 0)); // C major

        MidiKeyGuesser.KeyGuess guess = MidiKeyGuesser.detectKey(sequence, 0, null);

        assertTrue(guess.render().startsWith("C major"));
    }

    @Test
    void detectKey_guessesCmajorFromScaleNotes() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        int[] cMajor = new int[] {60, 62, 64, 65, 67, 69, 71, 72};
        long tick = 0;
        for (int note : cMajor) {
            addNoteOn(track, 0, note, 64, tick);
            tick += 120;
        }

        MidiKeyGuesser.KeyGuess guess = MidiKeyGuesser.detectKey(sequence, 0, 0);

        assertTrue(guess.render().startsWith("C major"));
    }

    @Test
    void transpose_shiftsKeyName() {
        MidiKeyGuesser.KeyGuess guess = MidiKeyGuesser.detectKey(buildKeySigSequence(), 0, null);
        MidiKeyGuesser.KeyGuess transposed = MidiKeyGuesser.transpose(guess, 2);

        assertTrue(transposed.render().startsWith("D major"));
    }

    private static Sequence buildKeySigSequence() {
        try {
            Sequence sequence = new Sequence(Sequence.PPQ, 480);
            Track track = sequence.createTrack();
            track.add(new MidiEvent(keySignatureEvent(0, 0), 0));
            return sequence;
        } catch (Exception e) {
            throw new IllegalStateException(e);
        }
    }

    private static MetaMessage keySignatureEvent(int sharpsFlats, int minorFlag) throws Exception {
        MetaMessage key = new MetaMessage();
        byte[] data = new byte[] {(byte) sharpsFlats, (byte) minorFlag};
        key.setMessage(0x59, data, data.length);
        return key;
    }

    private static void addNoteOn(Track track, int channel, int note, int velocity, long tick) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_ON, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }
}

