package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.MidiEvent;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class NoteRangeExtractorTest {

    @Test
    void extract_returnsDefaultsWhenNoNotes() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        sequence.createTrack();

        NoteRangeExtractor.NoteRange range = new NoteRangeExtractor().extract(sequence);

        assertEquals(-1, range.lowest());
        assertEquals(-1, range.highest());
        assertEquals(0, range.span());
        assertFalse(range.isValid());
    }

    @Test
    void extract_findsLowestAndHighestAcrossTracks() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track1 = sequence.createTrack();
        Track track2 = sequence.createTrack();

        addNoteOn(track1, 0, 72, 90, 0);
        addNoteOn(track1, 0, 60, 90, 240);
        addNoteOn(track2, 0, 84, 90, 0);

        NoteRangeExtractor.NoteRange range = new NoteRangeExtractor().extract(sequence);

        assertEquals(60, range.lowest());
        assertEquals(84, range.highest());
        assertEquals(24, range.span());
        assertTrue(range.isValid());
    }

    @Test
    void extract_ignoresVelocityZeroNoteOnEvents() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        addNoteOn(track, 0, 70, 0, 0);
        addNoteOn(track, 0, 64, 90, 120);

        NoteRangeExtractor.NoteRange range = new NoteRangeExtractor().extract(sequence);

        assertEquals(64, range.lowest());
        assertEquals(64, range.highest());
    }

    @Test
    void extract_filtersByChannelWhenProvided() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        addNoteOn(track, 0, 60, 90, 0);
        addNoteOn(track, 1, 72, 90, 120);

        NoteRangeExtractor.NoteRange range = new NoteRangeExtractor(1).extract(sequence);

        assertEquals(72, range.lowest());
        assertEquals(72, range.highest());
    }

    private static void addNoteOn(Track track, int channel, int note, int velocity, long tick)
            throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_ON, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }
}

