package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import javax.sound.midi.ShortMessage;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class NoteToImageTest {

    @Test
    @Disabled
    void mapNotesToImages_returnsImagesForMappedNotes() throws Exception {
        List<MidiNote> notes = new ArrayList<>();
        notes.add(buildMidiNote(69)); // A5
        notes.add(buildMidiNote(72)); // C6

        List<java.awt.image.BufferedImage> images = NoteToImage.mapNotesToImages(notes);

        assertEquals(2, images.size());
        assertNotNull(images.get(0));
        assertNotNull(images.get(1));
    }

    @Test
    void mapNotesToImages_throwsWhenNoNotes() {
        List<MidiNote> notes = new ArrayList<>();

        assertThrows(NoteProcessingException.class, () -> NoteToImage.mapNotesToImages(notes));
    }

    @Test
    void mapNotesToImages_throwsForOutOfRangeNote() throws Exception {
        List<MidiNote> notes = new ArrayList<>();
        notes.add(buildMidiNote(103)); // G7 (out of range for alto C twelve)

        assertThrows(OutOfRangeException.class, () -> NoteToImage.mapNotesToImages(notes));
    }

    private static MidiNote buildMidiNote(int noteValue) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_ON, 0, noteValue, 64);
        return new MidiNote(message, MidiUtils.formatNoteName(noteValue), noteValue, true, 64, 0L);
    }
}

