package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.MetaMessage;
import javax.sound.midi.MidiEvent;
import javax.sound.midi.MidiMessage;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class SkylineMelodyTransformerTest {

    @Test
    void transform_selectsHighestPitchDuringOverlap() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        addNoteOn(track, 0, 60, 64, 0);
        addNoteOn(track, 0, 72, 64, 240);
        addNoteOff(track, 0, 72, 64, 480);
        addNoteOff(track, 0, 60, 64, 720);

        SkylineMelodyTransformer transformer = new SkylineMelodyTransformer();
        Sequence output = transformer.transform(sequence);

        List<MidiEvent> shortEvents = shortMessageEvents(output.getTracks()[0]);

        assertEquals(6, shortEvents.size());
        assertShort(shortEvents.get(0), ShortMessage.NOTE_ON, 0, 60, 64, 0);
        assertShort(shortEvents.get(1), ShortMessage.NOTE_OFF, 0, 60, 0, 240);
        assertShort(shortEvents.get(2), ShortMessage.NOTE_ON, 0, 72, 64, 240);
        assertShort(shortEvents.get(3), ShortMessage.NOTE_OFF, 0, 72, 0, 480);
        assertShort(shortEvents.get(4), ShortMessage.NOTE_ON, 0, 60, 64, 480);
        assertShort(shortEvents.get(5), ShortMessage.NOTE_OFF, 0, 60, 0, 720);
    }

    @Test
    void transform_copiesMetaEventsAndAddsEot() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        MetaMessage name = new MetaMessage();
        byte[] data = "track-name".getBytes();
        name.setMessage(0x03, data, data.length);
        track.add(new MidiEvent(name, 0));

        addNoteOn(track, 0, 64, 64, 0);
        addNoteOff(track, 0, 64, 64, 240);

        SkylineMelodyTransformer transformer = new SkylineMelodyTransformer();
        Sequence output = transformer.transform(sequence);

        Track outTrack = output.getTracks()[0];
        boolean hasName = false;
        boolean hasEot = false;

        for (int i = 0; i < outTrack.size(); i++) {
            MidiMessage msg = outTrack.get(i).getMessage();
            if (msg instanceof MetaMessage meta) {
                if (meta.getType() == 0x03) {
                    hasName = true;
                }
                if (meta.getType() == 0x2F) {
                    hasEot = true;
                }
            }
        }

        assertTrue(hasName);
        assertTrue(hasEot);
    }

    @Test
    void transform_treatsNoteOnVelocityZeroAsOff() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        addNoteOn(track, 3, 65, 90, 0);
        addNoteOn(track, 3, 65, 0, 240);

        SkylineMelodyTransformer transformer = new SkylineMelodyTransformer();
        Sequence output = transformer.transform(sequence);

        List<MidiEvent> shortEvents = shortMessageEvents(output.getTracks()[0]);

        assertEquals(2, shortEvents.size());
        assertShort(shortEvents.get(0), ShortMessage.NOTE_ON, 3, 65, 90, 0);
        assertShort(shortEvents.get(1), ShortMessage.NOTE_OFF, 3, 65, 0, 240);
    }

    @Test
    void transform_mergesAdjacentSamePitchSegments() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        addNoteOn(track, 0, 64, 70, 0);
        addNoteOff(track, 0, 64, 64, 240);
        addNoteOn(track, 0, 64, 80, 240);
        addNoteOff(track, 0, 64, 64, 480);

        SkylineMelodyTransformer transformer = new SkylineMelodyTransformer();
        Sequence output = transformer.transform(sequence);

        List<MidiEvent> shortEvents = shortMessageEvents(output.getTracks()[0]);

        assertEquals(2, shortEvents.size());
        assertShort(shortEvents.get(0), ShortMessage.NOTE_ON, 0, 64, 80, 0);
        assertShort(shortEvents.get(1), ShortMessage.NOTE_OFF, 0, 64, 0, 480);
    }

    private static List<MidiEvent> shortMessageEvents(Track track) {
        List<MidiEvent> events = new ArrayList<>();
        for (int i = 0; i < track.size(); i++) {
            if (track.get(i).getMessage() instanceof ShortMessage) {
                events.add(track.get(i));
            }
        }
        return events;
    }

    private static void assertShort(MidiEvent event, int command, int channel, int note, int velocity, long tick) {
        ShortMessage sm = (ShortMessage) event.getMessage();
        assertEquals(command, sm.getCommand());
        assertEquals(channel, sm.getChannel());
        assertEquals(note, sm.getData1());
        assertEquals(velocity, sm.getData2());
        assertEquals(tick, event.getTick());
    }

    private static void addNoteOn(Track track, int channel, int note, int velocity, long tick) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_ON, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }

    private static void addNoteOff(Track track, int channel, int note, int velocity, long tick) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_OFF, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }
}
