package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.MetaMessage;
import javax.sound.midi.MidiEvent;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class TempoAwareDurationsTest {

    @Test
    void extractDurations_throwsOnNullSequence() {
        assertThrows(IllegalArgumentException.class, () ->
                TempoAwareDurations.extractDurations(null, List.of(), List.of())
        );
    }

    @Test
    void extractDurations_throwsOnNonPpqSequence() throws Exception {
        Sequence sequence = new Sequence(Sequence.SMPTE_24, 10);

        assertThrows(IllegalArgumentException.class, () ->
                TempoAwareDurations.extractDurations(sequence, List.of(), List.of())
        );
    }

    @Test
    void extractDurations_returnsEmptyWhenNotesMissing() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        sequence.createTrack();

        assertTrue(TempoAwareDurations.extractDurations(sequence, null, null).isEmpty());
        assertTrue(TempoAwareDurations.extractDurations(sequence, List.of(), List.of()).isEmpty());
    }

    @Test
    void extractDurations_usesDefaultTempoWhenNoTempoEvents() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        sequence.createTrack();

        List<MidiNote> onNotes = new ArrayList<>();
        List<MidiNote> offNotes = new ArrayList<>();

        onNotes.add(buildNote(60, 0));
        onNotes.add(buildNote(60, 480));
        onNotes.add(buildNote(60, 960));

        offNotes.add(buildNote(60, 480));
        offNotes.add(buildNote(60, 960));
        offNotes.add(buildNote(60, 1440));

        List<Double> durations = TempoAwareDurations.extractDurations(sequence, onNotes, offNotes);

        assertEquals(3, durations.size());
        assertEquals(500.0, durations.get(0), 0.001);
        assertEquals(500.0, durations.get(1), 0.001);
        assertEquals(500.0, durations.get(2), 0.001);
    }

    @Test
    void extractDurations_respectsTempoChanges() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        track.add(tempoEvent(0, 500_000)); // 120 BPM
        track.add(tempoEvent(480, 1_000_000)); // 60 BPM

        List<MidiNote> onNotes = new ArrayList<>();
        List<MidiNote> offNotes = new ArrayList<>();

        onNotes.add(buildNote(60, 0));
        onNotes.add(buildNote(60, 480));
        onNotes.add(buildNote(60, 960));

        offNotes.add(buildNote(60, 480));
        offNotes.add(buildNote(60, 960));
        offNotes.add(buildNote(60, 1440));

        List<Double> durations = TempoAwareDurations.extractDurations(sequence, onNotes, offNotes);

        assertEquals(3, durations.size());
        assertEquals(500.0, durations.get(0), 0.001);
        assertEquals(1000.0, durations.get(1), 0.001);
        assertEquals(1000.0, durations.get(2), 0.001);
    }

    @Test
    void extractDurations_guardsAgainstZeroLength() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        sequence.createTrack();

        List<MidiNote> onNotes = new ArrayList<>();
        List<MidiNote> offNotes = new ArrayList<>();

        onNotes.add(buildNote(60, 0));
        onNotes.add(buildNote(60, 0));

        offNotes.add(buildNote(60, 0));
        offNotes.add(buildNote(60, 0));

        List<Double> durations = TempoAwareDurations.extractDurations(sequence, onNotes, offNotes);

        assertEquals(2, durations.size());
        assertTrue(durations.get(0) > 0.0);
        assertTrue(durations.get(1) > 0.0);
    }

    private static MidiNote buildNote(int noteValue, long tick) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_ON, 0, noteValue, 64);
        return new MidiNote(message, MidiUtils.formatNoteName(noteValue), noteValue, true, 64, tick);
    }

    private static MidiEvent tempoEvent(long tick, int mpq) throws Exception {
        MetaMessage tempo = new MetaMessage();
        byte[] data = new byte[] {
                (byte) ((mpq >> 16) & 0xFF),
                (byte) ((mpq >> 8) & 0xFF),
                (byte) (mpq & 0xFF)
        };
        tempo.setMessage(0x51, data, data.length);
        return new MidiEvent(tempo, tick);
    }
}

