package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.MidiEvent;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class TrackExtractorTest {

    @Test
    void guessMelodyChannel_selectsHighestTopNoteAtTick() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        addNoteOn(track, 0, 60, 64, 0);
        addNoteOn(track, 1, 72, 64, 0);

        assertEquals(1, TrackExtractor.guessMelodyChannel(track));
    }

    @Test
    void guessMelodyChannel_selectsChannelWithMostTopNoteWins() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        addNoteOn(track, 1, 70, 64, 0);
        addNoteOn(track, 2, 72, 64, 0);

        addNoteOn(track, 1, 75, 64, 480);
        addNoteOn(track, 2, 74, 64, 480);

        addNoteOn(track, 2, 80, 64, 960);
        addNoteOn(track, 1, 79, 64, 960);

        assertEquals(2, TrackExtractor.guessMelodyChannel(track));
    }

    @Test
    void guessMelodyChannel_returnsZeroWhenNoNotes() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480);
        Track track = sequence.createTrack();

        assertEquals(0, TrackExtractor.guessMelodyChannel(track));
    }

    private static void addNoteOn(Track track, int channel, int note, int velocity, long tick)
            throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_ON, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }
}

