package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.MidiEvent;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class TransposerTest {

    @Test
    void transform_transposesNotesUpToFitRange() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480, 1);
        Track track = sequence.getTracks()[0];

        addNoteOn(track, 0, 60, 64, 0);
        addNoteOff(track, 0, 60, 64, 240);

        Transposer transposer = new Transposer(0, 60, 60, Ocarinas.C_SOPRANO);
        Sequence output = transposer.transform(sequence);

        Track outTrack = output.getTracks()[0];
        ShortMessage on = (ShortMessage) outTrack.get(0).getMessage();
        ShortMessage off = (ShortMessage) outTrack.get(1).getMessage();

        assertEquals(ShortMessage.NOTE_ON, on.getCommand());
        assertEquals(69, on.getData1());
        assertEquals(ShortMessage.NOTE_OFF, off.getCommand());
        assertEquals(69, off.getData1());
    }

    @Test
    void transform_keepsNotesInRangeWithoutShift() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480, 1);
        Track track = sequence.getTracks()[0];

        addNoteOn(track, 0, 70, 64, 0);
        addNoteOff(track, 0, 70, 64, 240);

        Transposer transposer = new Transposer(0, 70, 70, Ocarinas.C_SOPRANO);
        Sequence output = transposer.transform(sequence);

        Track outTrack = output.getTracks()[0];
        ShortMessage on = (ShortMessage) outTrack.get(0).getMessage();
        ShortMessage off = (ShortMessage) outTrack.get(1).getMessage();

        assertEquals(70, on.getData1());
        assertEquals(70, off.getData1());
    }

    @Test
    void transform_octaveFoldsWhenSpanExceedsRange() throws Exception {
        // C5 (60) to Eb7 (87) — span of 27, ocarina range is 20 (A5=69 to F7=89)
        Sequence sequence = new Sequence(Sequence.PPQ, 480, 1);
        Track track = sequence.getTracks()[0];

        addNoteOn(track, 0, 60, 64, 0);     // C5
        addNoteOff(track, 0, 60, 64, 240);
        addNoteOn(track, 0, 87, 64, 480);    // Eb7
        addNoteOff(track, 0, 87, 64, 720);

        Transposer transposer = new Transposer(0, 60, 87, Ocarinas.C_SOPRANO);
        Sequence output = transposer.transform(sequence);

        Track outTrack = output.getTracks()[0];

        // All notes should be within the ocarina range [69, 89]
        for (int i = 0; i < outTrack.size(); i++) {
            if (outTrack.get(i).getMessage() instanceof ShortMessage sm) {
                int cmd = sm.getCommand();
                if (cmd == ShortMessage.NOTE_ON || cmd == ShortMessage.NOTE_OFF) {
                    int pitch = sm.getData1();
                    assertTrue(pitch >= 69 && pitch <= 89,
                            "Pitch " + pitch + " is outside ocarina range [69, 89]");
                }
            }
        }
    }

    @Test
    void transform_octaveFoldsNotesBelowRange() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480, 1);
        Track track = sequence.getTracks()[0];

        // A note well below and one within range
        addNoteOn(track, 0, 50, 64, 0);     // D4
        addNoteOff(track, 0, 50, 64, 240);
        addNoteOn(track, 0, 85, 64, 480);    // C#7
        addNoteOff(track, 0, 85, 64, 720);

        Transposer transposer = new Transposer(0, 50, 85, Ocarinas.C_SOPRANO);
        Sequence output = transposer.transform(sequence);

        Track outTrack = output.getTracks()[0];
        for (int i = 0; i < outTrack.size(); i++) {
            if (outTrack.get(i).getMessage() instanceof ShortMessage sm) {
                int cmd = sm.getCommand();
                if (cmd == ShortMessage.NOTE_ON || cmd == ShortMessage.NOTE_OFF) {
                    int pitch = sm.getData1();
                    assertTrue(pitch >= 69 && pitch <= 89,
                            "Pitch " + pitch + " is outside ocarina range [69, 89]");
                }
            }
        }
    }

    private static void addNoteOn(Track track, int channel, int note, int velocity, long tick) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_ON, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }

    private static void addNoteOff(Track track, int channel, int note, int velocity, long tick) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_OFF, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }
}

