package io.ryanjames.oak.midi;

import org.junit.jupiter.api.Test;

import javax.sound.midi.MidiEvent;
import javax.sound.midi.Sequence;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class TransposerTest {

    @Test
    void transform_transposesNotesUpToFitRange() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480, 1);
        Track track = sequence.getTracks()[0];

        addNoteOn(track, 0, 60, 64, 0);
        addNoteOff(track, 0, 60, 64, 240);

        Transposer transposer = new Transposer(0, 60, 60, Ocarinas.C_SOPRANO);
        Sequence output = transposer.transform(sequence);

        Track outTrack = output.getTracks()[0];
        ShortMessage on = (ShortMessage) outTrack.get(0).getMessage();
        ShortMessage off = (ShortMessage) outTrack.get(1).getMessage();

        assertEquals(ShortMessage.NOTE_ON, on.getCommand());
        assertEquals(69, on.getData1());
        assertEquals(ShortMessage.NOTE_OFF, off.getCommand());
        assertEquals(69, off.getData1());
    }

    @Test
    void transform_keepsNotesInRangeWithoutShift() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480, 1);
        Track track = sequence.getTracks()[0];

        addNoteOn(track, 0, 70, 64, 0);
        addNoteOff(track, 0, 70, 64, 240);

        Transposer transposer = new Transposer(0, 70, 70, Ocarinas.C_SOPRANO);
        Sequence output = transposer.transform(sequence);

        Track outTrack = output.getTracks()[0];
        ShortMessage on = (ShortMessage) outTrack.get(0).getMessage();
        ShortMessage off = (ShortMessage) outTrack.get(1).getMessage();

        assertEquals(70, on.getData1());
        assertEquals(70, off.getData1());
    }

    @Test
    void transform_throwsWhenSpanTooWide() throws Exception {
        Sequence sequence = new Sequence(Sequence.PPQ, 480, 1);
        Track track = sequence.getTracks()[0];

        addNoteOn(track, 0, 40, 64, 0);
        addNoteOff(track, 0, 40, 64, 240);
        addNoteOn(track, 0, 110, 64, 480);
        addNoteOff(track, 0, 110, 64, 720);

        Transposer transposer = new Transposer(0, 40, 110, Ocarinas.C_SOPRANO);

        assertThrows(OutOfRangeException.class, () -> transposer.transform(sequence));
    }

    private static void addNoteOn(Track track, int channel, int note, int velocity, long tick) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_ON, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }

    private static void addNoteOff(Track track, int channel, int note, int velocity, long tick) throws Exception {
        ShortMessage message = new ShortMessage();
        message.setMessage(ShortMessage.NOTE_OFF, channel, note, velocity);
        track.add(new MidiEvent(message, tick));
    }
}

