package io.ryanjames.oak.config;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleModule;
import org.junit.jupiter.api.Test;

import java.awt.Color;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class ColorDeserializerTest {

    @Test
    void deserialize_returnsNullForBlankOrNull() throws Exception {
        ObjectMapper mapper = buildMapper();

        Color blank = mapper.readValue("\"   \"", Color.class);
        Color empty = mapper.readValue("\"\"", Color.class);

        assertNull(blank);
        assertNull(empty);
    }

    @Test
    void deserialize_parsesSixDigitHexWithOrWithoutHash() throws Exception {
        ObjectMapper mapper = buildMapper();

        Color withHash = mapper.readValue("\"#00FF7F\"", Color.class);
        Color noHash = mapper.readValue("\"00FF7F\"", Color.class);

        assertEquals(new Color(0x00FF7F), withHash);
        assertEquals(new Color(0x00FF7F), noHash);
    }

    @Test
    void deserialize_parsesEightDigitHexAsArgb() throws Exception {
        ObjectMapper mapper = buildMapper();

        Color color = mapper.readValue("\"80FF0000\"", Color.class);

        assertEquals(new Color(255, 0, 0, 128), color);
    }

    @Test
    void deserialize_rejectsInvalidLength() throws Exception {
        ObjectMapper mapper = buildMapper();

        IOException thrown = assertThrows(IOException.class, () ->
                mapper.readValue("\"FFF\"", Color.class)
        );

        assertTrue(thrown.getMessage().endsWith("Invalid color format: #FFF"));
    }

    private static ObjectMapper buildMapper() {
        SimpleModule module = new SimpleModule();
        module.addDeserializer(Color.class, new ColorDeserializer());
        return new ObjectMapper().registerModule(module);
    }
}
