package io.ryanjames.oak.config;

import io.ryanjames.oak.CommandLineException;
import io.ryanjames.oak.VideoConfig;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.junit.jupiter.api.Test;

import java.awt.Color;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests generated by AI (GPT-5.2-Codex) and not checked by a human.
 */
class VideoArgParserTest {

    @Test
    void fromCmd_defaultsPdfAndVidWhenNeitherSpecified() throws Exception {
        CommandLine cmd = parse();

        VideoConfig config = VideoArgParser.fromCmd(cmd);

        assertTrue(config.isOutputPdf());
        assertTrue(config.isOutputVid());
    }

    @Test
    void fromCmd_setsOutputFlagsFromOptions() throws Exception {
        CommandLine cmd = parse("-pdf");

        VideoConfig config = VideoArgParser.fromCmd(cmd);

        assertTrue(config.isOutputPdf());
        assertFalse(config.isOutputVid());
    }

    @Test
    void fromCmd_parsesDimensionsAndColors() throws Exception {
        CommandLine cmd = parse("-d", "4", "-c", "255 0 0", "-co", "0 255 0", "-cp", "0 0 255");

        VideoConfig config = VideoArgParser.fromCmd(cmd);

        assertEquals(4, config.getDims());
        assertEquals(new Color(255, 0, 0), config.getNoteOnColor());
        assertEquals(new Color(0, 255, 0), config.getNoteOffColor());
        assertEquals(new Color(0, 0, 255), config.getPreviewNoteColor());
    }

    @Test
    void fromCmd_invalidFpsKeepsDefault() throws Exception {
        CommandLine cmd = parse("-fr", "200");

        VideoConfig config = VideoArgParser.fromCmd(cmd);

        assertEquals(60, config.getFramerate());
    }

    @Test
    void fromCmd_validFpsUpdatesValue() throws Exception {
        CommandLine cmd = parse("-fr", "120");

        VideoConfig config = VideoArgParser.fromCmd(cmd);

        assertEquals(120, config.getFramerate());
    }

    @Test
    void fromCmd_parsesOffsetAndMidiPath() throws Exception {
        CommandLine cmd = parse("-ofs", "1.25", "-i", "song.mid");

        VideoConfig config = VideoArgParser.fromCmd(cmd);

        assertEquals(1.25, config.getAudioOffset());
        assertEquals("song.mid", config.getMidiFilePath());
    }

    @Test
    void fromCmd_validOutputPathIsAccepted() throws Exception {
        Path tempDir = Files.createTempDirectory("oak-out");
        Path outputPath = tempDir.resolve("video.mp4");

        CommandLine cmd = parse("-o", outputPath.toString());

        VideoConfig config = VideoArgParser.fromCmd(cmd);

        assertEquals(outputPath.toString(), config.getOutputDir());
    }

    @Test
    void fromCmd_invalidOutputPathThrows() throws Exception {
        Path tempDir = Files.createTempDirectory("oak-out");
        Path outputPath = tempDir.resolve("missing").resolve("video.mp4");

        CommandLine cmd = parse("-o", outputPath.toString());

        assertThrows(CommandLineException.class, () -> VideoArgParser.fromCmd(cmd));
    }

    @Test
    void fromCmd_audioFileSetsSourceFlags() throws Exception {
        Path audioFile = Files.createTempFile("oak-audio", ".wav");

        CommandLine cmd = parse("-a", audioFile.toString());

        VideoConfig config = VideoArgParser.fromCmd(cmd);

        assertFalse(config.isAudioFromMidi());
        assertEquals(audioFile.toString(), config.getAudioFilePath());
    }

    @Test
    void fromCmd_missingAudioFileUsesMidi() throws Exception {
        CommandLine cmd = parse();

        VideoConfig config = VideoArgParser.fromCmd(cmd);

        assertTrue(config.isAudioFromMidi());
        assertEquals("", config.getAudioFilePath());
    }

    private static CommandLine parse(String... args) throws Exception {
        Options options = new Options();
        options.addOption(Option.builder("pdf").build());
        options.addOption(Option.builder("vid").build());
        options.addOption(Option.builder("d").hasArg().build());
        options.addOption(Option.builder("c").hasArg().build());
        options.addOption(Option.builder("co").hasArg().build());
        options.addOption(Option.builder("cp").hasArg().build());
        options.addOption(Option.builder("fr").hasArg().build());
        options.addOption(Option.builder("ofs").hasArg().build());
        options.addOption(Option.builder("i").hasArg().build());
        options.addOption(Option.builder("o").hasArg().build());
        options.addOption(Option.builder("a").hasArg().build());
        return new DefaultParser().parse(options, args);
    }
}

